//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSI.WCFTesting.UpdateResultServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnvironmentalConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthOfStayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalCharacterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderMovableIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingArea {
            get {
                return this.BuildingAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingAreaField, value) != true)) {
                    this.BuildingAreaField = value;
                    this.RaisePropertyChanged("BuildingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnvironmentalConditions {
            get {
                return this.EnvironmentalConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvironmentalConditionsField, value) != true)) {
                    this.EnvironmentalConditionsField = value;
                    this.RaisePropertyChanged("EnvironmentalConditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseStatus {
            get {
                return this.HouseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseStatusField, value) != true)) {
                    this.HouseStatusField = value;
                    this.RaisePropertyChanged("HouseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LengthOfStay {
            get {
                return this.LengthOfStayField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthOfStayField, value) != true)) {
                    this.LengthOfStayField = value;
                    this.RaisePropertyChanged("LengthOfStay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalCharacter {
            get {
                return this.PersonalCharacterField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalCharacterField, value) != true)) {
                    this.PersonalCharacterField = value;
                    this.RaisePropertyChanged("PersonalCharacter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidenceConditions {
            get {
                return this.ResidenceConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceConditionsField, value) != true)) {
                    this.ResidenceConditionsField = value;
                    this.RaisePropertyChanged("ResidenceConditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderMovableID {
            get {
                return this.WorkOrderMovableIDField;
            }
            set {
                if ((this.WorkOrderMovableIDField.Equals(value) != true)) {
                    this.WorkOrderMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderMovableID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultPhotoAdditionalMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultPhotoAdditionalMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultPhotoAdditionalMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultPhotoAdditionalMovableID {
            get {
                return this.ResultPhotoAdditionalMovableIDField;
            }
            set {
                if ((this.ResultPhotoAdditionalMovableIDField.Equals(value) != true)) {
                    this.ResultPhotoAdditionalMovableIDField = value;
                    this.RaisePropertyChanged("ResultPhotoAdditionalMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultReqDocMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultReqDocMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReqDocMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultReqDocMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReqDocMovableID {
            get {
                return this.ReqDocMovableIDField;
            }
            set {
                if ((this.ReqDocMovableIDField.Equals(value) != true)) {
                    this.ReqDocMovableIDField = value;
                    this.RaisePropertyChanged("ReqDocMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultReqDocMovableID {
            get {
                return this.ResultReqDocMovableIDField;
            }
            set {
                if ((this.ResultReqDocMovableIDField.Equals(value) != true)) {
                    this.ResultReqDocMovableIDField = value;
                    this.RaisePropertyChanged("ResultReqDocMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingPeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCondition {
            get {
                return this.CompanyConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyConditionField, value) != true)) {
                    this.CompanyConditionField = value;
                    this.RaisePropertyChanged("CompanyCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyPeriod {
            get {
                return this.CompanyPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPeriodField, value) != true)) {
                    this.CompanyPeriodField = value;
                    this.RaisePropertyChanged("CompanyPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderNotMovableID {
            get {
                return this.WorkOrderNotMovableIDField;
            }
            set {
                if ((this.WorkOrderNotMovableIDField.Equals(value) != true)) {
                    this.WorkOrderNotMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingPeriod {
            get {
                return this.WorkingPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingPeriodField, value) != true)) {
                    this.WorkingPeriodField = value;
                    this.RaisePropertyChanged("WorkingPeriod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultPhotoAdditionalNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultPhotoAdditionalNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultPhotoAdditionalNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultPhotoAdditionalNotMovableID {
            get {
                return this.ResultPhotoAdditionalNotMovableIDField;
            }
            set {
                if ((this.ResultPhotoAdditionalNotMovableIDField.Equals(value) != true)) {
                    this.ResultPhotoAdditionalNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultPhotoAdditionalNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultReqDocNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCoreSystem")]
    [System.SerializableAttribute()]
    public partial class TrResultReqDocNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReqDocNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultReqDocNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReqDocNotMovableID {
            get {
                return this.ReqDocNotMovableIDField;
            }
            set {
                if ((this.ReqDocNotMovableIDField.Equals(value) != true)) {
                    this.ReqDocNotMovableIDField = value;
                    this.RaisePropertyChanged("ReqDocNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultReqDocNotMovableID {
            get {
                return this.ResultReqDocNotMovableIDField;
            }
            set {
                if ((this.ResultReqDocNotMovableIDField.Equals(value) != true)) {
                    this.ResultReqDocNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultReqDocNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateResultServiceReference.IUpdateResultService")]
    public interface IUpdateResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultMovableCoreSystemBundle", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultMovableCoreSystemBundleRespon" +
            "se")]
        bool InsertResultMovableCoreSystemBundle(GSI.WCFTesting.UpdateResultServiceReference.TrResultMovable _prmResultMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList, ref string _errMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultMovableCoreSystem", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultMovableCoreSystemResponse")]
        void InsertResultMovableCoreSystem(GSI.WCFTesting.UpdateResultServiceReference.TrResultMovable _prmResultMovable, ref long _resultID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultPhotoAddtMovableCoreSystem", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultPhotoAddtMovableCoreSystemRes" +
            "ponse")]
        void InsertResultPhotoAddtMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultReqDocMovableCoreSystem", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultReqDocMovableCoreSystemRespon" +
            "se")]
        void InsertResultReqDocMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultNotMovableCoreSystemBundle", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultNotMovableCoreSystemBundleRes" +
            "ponse")]
        bool InsertResultNotMovableCoreSystemBundle(GSI.WCFTesting.UpdateResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList, ref string _errMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultNotMovableCoreSystem", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultNotMovableCoreSystemResponse")]
        void InsertResultNotMovableCoreSystem(GSI.WCFTesting.UpdateResultServiceReference.TrResultNotMovable _prmResultNotMovable, ref long _resultID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultPhotoAddtNotMovableCoreSystem" +
            "", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultPhotoAddtNotMovableCoreSystem" +
            "Response")]
        void InsertResultPhotoAddtNotMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateResultService/InsertResultReqDocNotMovableCoreSystem", ReplyAction="http://tempuri.org/IUpdateResultService/InsertResultReqDocNotMovableCoreSystemRes" +
            "ponse")]
        void InsertResultReqDocNotMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateResultServiceChannel : GSI.WCFTesting.UpdateResultServiceReference.IUpdateResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateResultServiceClient : System.ServiceModel.ClientBase<GSI.WCFTesting.UpdateResultServiceReference.IUpdateResultService>, GSI.WCFTesting.UpdateResultServiceReference.IUpdateResultService {
        
        public UpdateResultServiceClient() {
        }
        
        public UpdateResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertResultMovableCoreSystemBundle(GSI.WCFTesting.UpdateResultServiceReference.TrResultMovable _prmResultMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList, ref string _errMessage) {
            return base.Channel.InsertResultMovableCoreSystemBundle(_prmResultMovable, _prmResultPhotoAddtMovable, _prmResultReqDocMovableList, ref _errMessage);
        }
        
        public void InsertResultMovableCoreSystem(GSI.WCFTesting.UpdateResultServiceReference.TrResultMovable _prmResultMovable, ref long _resultID) {
            base.Channel.InsertResultMovableCoreSystem(_prmResultMovable, ref _resultID);
        }
        
        public void InsertResultPhotoAddtMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable) {
            base.Channel.InsertResultPhotoAddtMovableCoreSystem(_resultID, _prmResultPhotoAddtMovable);
        }
        
        public void InsertResultReqDocMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList) {
            base.Channel.InsertResultReqDocMovableCoreSystem(_resultID, _prmResultReqDocMovableList);
        }
        
        public bool InsertResultNotMovableCoreSystemBundle(GSI.WCFTesting.UpdateResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList, ref string _errMessage) {
            return base.Channel.InsertResultNotMovableCoreSystemBundle(_prmResultNotMovable, _prmResultPhotoAddtNotMovable, _prmResultReqDocNotMovableList, ref _errMessage);
        }
        
        public void InsertResultNotMovableCoreSystem(GSI.WCFTesting.UpdateResultServiceReference.TrResultNotMovable _prmResultNotMovable, ref long _resultID) {
            base.Channel.InsertResultNotMovableCoreSystem(_prmResultNotMovable, ref _resultID);
        }
        
        public void InsertResultPhotoAddtNotMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable) {
            base.Channel.InsertResultPhotoAddtNotMovableCoreSystem(_resultID, _prmResultPhotoAddtNotMovable);
        }
        
        public void InsertResultReqDocNotMovableCoreSystem(long _resultID, GSI.WCFTesting.UpdateResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList) {
            base.Channel.InsertResultReqDocNotMovableCoreSystem(_resultID, _prmResultReqDocNotMovableList);
        }
    }
}
