//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSIWebsiteCore.UpdateCPResultServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateCPResultServiceReference.IUpdateCPResultService")]
    public interface IUpdateCPResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateCPResultService/UpdateResultMovableCustomerPortal", ReplyAction="http://tempuri.org/IUpdateCPResultService/UpdateResultMovableCustomerPortalRespon" +
            "se")]
        void UpdateResultMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderMovable _prmWorkOrderMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultMovable _prmResultMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateCPResultService/UpdateResultNotMovableCustomerPortal", ReplyAction="http://tempuri.org/IUpdateCPResultService/UpdateResultNotMovableCustomerPortalRes" +
            "ponse")]
        void UpdateResultNotMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderNotMovable _prmWorkOrderNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateCPResultServiceChannel : GSIWebsiteCore.UpdateCPResultServiceReference.IUpdateCPResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCPResultServiceClient : System.ServiceModel.ClientBase<GSIWebsiteCore.UpdateCPResultServiceReference.IUpdateCPResultService>, GSIWebsiteCore.UpdateCPResultServiceReference.IUpdateCPResultService {
        
        public UpdateCPResultServiceClient() {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateResultMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderMovable _prmWorkOrderMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultMovable _prmResultMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList) {
            base.Channel.UpdateResultMovableCustomerPortal(_prmWorkOrderMovable, _prmResultMovable, _prmResultPhotoAddtMovable, _prmResultReqDocMovableList);
        }
        
        public void UpdateResultNotMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderNotMovable _prmWorkOrderNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList) {
            base.Channel.UpdateResultNotMovableCustomerPortal(_prmWorkOrderNotMovable, _prmResultNotMovable, _prmResultPhotoAddtNotMovable, _prmResultReqDocNotMovableList);
        }
    }
}
