//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSI.BusinessRuleCore.UpdateCPResultServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrWorkOrderMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrWorkOrderMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExecuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DownloadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnTheSpotDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnTheWayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderSPMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SurveyResultReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SurveyorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SyncStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkOrderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte WorkOrderStatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExecute {
            get {
                return this.DateExecuteField;
            }
            set {
                if ((this.DateExecuteField.Equals(value) != true)) {
                    this.DateExecuteField = value;
                    this.RaisePropertyChanged("DateExecute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DownloadDate {
            get {
                return this.DownloadDateField;
            }
            set {
                if ((this.DownloadDateField.Equals(value) != true)) {
                    this.DownloadDateField = value;
                    this.RaisePropertyChanged("DownloadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnTheSpotDate {
            get {
                return this.OnTheSpotDateField;
            }
            set {
                if ((this.OnTheSpotDateField.Equals(value) != true)) {
                    this.OnTheSpotDateField = value;
                    this.RaisePropertyChanged("OnTheSpotDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnTheWayDate {
            get {
                return this.OnTheWayDateField;
            }
            set {
                if ((this.OnTheWayDateField.Equals(value) != true)) {
                    this.OnTheWayDateField = value;
                    this.RaisePropertyChanged("OnTheWayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderSPMovableID {
            get {
                return this.OrderSPMovableIDField;
            }
            set {
                if ((this.OrderSPMovableIDField.Equals(value) != true)) {
                    this.OrderSPMovableIDField = value;
                    this.RaisePropertyChanged("OrderSPMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SurveyResultReceivedDate {
            get {
                return this.SurveyResultReceivedDateField;
            }
            set {
                if ((this.SurveyResultReceivedDateField.Equals(value) != true)) {
                    this.SurveyResultReceivedDateField = value;
                    this.RaisePropertyChanged("SurveyResultReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SurveyorID {
            get {
                return this.SurveyorIDField;
            }
            set {
                if ((this.SurveyorIDField.Equals(value) != true)) {
                    this.SurveyorIDField = value;
                    this.RaisePropertyChanged("SurveyorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SyncStatus {
            get {
                return this.SyncStatusField;
            }
            set {
                if ((this.SyncStatusField.Equals(value) != true)) {
                    this.SyncStatusField = value;
                    this.RaisePropertyChanged("SyncStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOrderCode {
            get {
                return this.WorkOrderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderCodeField, value) != true)) {
                    this.WorkOrderCodeField = value;
                    this.RaisePropertyChanged("WorkOrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderMovableID {
            get {
                return this.WorkOrderMovableIDField;
            }
            set {
                if ((this.WorkOrderMovableIDField.Equals(value) != true)) {
                    this.WorkOrderMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte WorkOrderStatusID {
            get {
                return this.WorkOrderStatusIDField;
            }
            set {
                if ((this.WorkOrderStatusIDField.Equals(value) != true)) {
                    this.WorkOrderStatusIDField = value;
                    this.RaisePropertyChanged("WorkOrderStatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnvironmentalConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthOfStayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalCharacterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingPeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingArea {
            get {
                return this.BuildingAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingAreaField, value) != true)) {
                    this.BuildingAreaField = value;
                    this.RaisePropertyChanged("BuildingArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnvironmentalConditions {
            get {
                return this.EnvironmentalConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvironmentalConditionsField, value) != true)) {
                    this.EnvironmentalConditionsField = value;
                    this.RaisePropertyChanged("EnvironmentalConditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseStatus {
            get {
                return this.HouseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseStatusField, value) != true)) {
                    this.HouseStatusField = value;
                    this.RaisePropertyChanged("HouseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LengthOfStay {
            get {
                return this.LengthOfStayField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthOfStayField, value) != true)) {
                    this.LengthOfStayField = value;
                    this.RaisePropertyChanged("LengthOfStay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalCharacter {
            get {
                return this.PersonalCharacterField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalCharacterField, value) != true)) {
                    this.PersonalCharacterField = value;
                    this.RaisePropertyChanged("PersonalCharacter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidenceConditions {
            get {
                return this.ResidenceConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceConditionsField, value) != true)) {
                    this.ResidenceConditionsField = value;
                    this.RaisePropertyChanged("ResidenceConditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderMovableID {
            get {
                return this.WorkOrderMovableIDField;
            }
            set {
                if ((this.WorkOrderMovableIDField.Equals(value) != true)) {
                    this.WorkOrderMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingPeriod {
            get {
                return this.WorkingPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingPeriodField, value) != true)) {
                    this.WorkingPeriodField = value;
                    this.RaisePropertyChanged("WorkingPeriod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultPhotoAdditionalMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultPhotoAdditionalMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultPhotoAdditionalMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultPhotoAdditionalMovableID {
            get {
                return this.ResultPhotoAdditionalMovableIDField;
            }
            set {
                if ((this.ResultPhotoAdditionalMovableIDField.Equals(value) != true)) {
                    this.ResultPhotoAdditionalMovableIDField = value;
                    this.RaisePropertyChanged("ResultPhotoAdditionalMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultReqDocMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultReqDocMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReqDocMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultReqDocMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReqDocMovableID {
            get {
                return this.ReqDocMovableIDField;
            }
            set {
                if ((this.ReqDocMovableIDField.Equals(value) != true)) {
                    this.ReqDocMovableIDField = value;
                    this.RaisePropertyChanged("ReqDocMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultMovableID {
            get {
                return this.ResultMovableIDField;
            }
            set {
                if ((this.ResultMovableIDField.Equals(value) != true)) {
                    this.ResultMovableIDField = value;
                    this.RaisePropertyChanged("ResultMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultReqDocMovableID {
            get {
                return this.ResultReqDocMovableIDField;
            }
            set {
                if ((this.ResultReqDocMovableIDField.Equals(value) != true)) {
                    this.ResultReqDocMovableIDField = value;
                    this.RaisePropertyChanged("ResultReqDocMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrWorkOrderNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrWorkOrderNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateExecuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DownloadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnTheSpotDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnTheWayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderSPNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SurveyResultReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SurveyorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SyncStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkOrderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte WorkOrderStatusIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateExecute {
            get {
                return this.DateExecuteField;
            }
            set {
                if ((this.DateExecuteField.Equals(value) != true)) {
                    this.DateExecuteField = value;
                    this.RaisePropertyChanged("DateExecute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DownloadDate {
            get {
                return this.DownloadDateField;
            }
            set {
                if ((this.DownloadDateField.Equals(value) != true)) {
                    this.DownloadDateField = value;
                    this.RaisePropertyChanged("DownloadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnTheSpotDate {
            get {
                return this.OnTheSpotDateField;
            }
            set {
                if ((this.OnTheSpotDateField.Equals(value) != true)) {
                    this.OnTheSpotDateField = value;
                    this.RaisePropertyChanged("OnTheSpotDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnTheWayDate {
            get {
                return this.OnTheWayDateField;
            }
            set {
                if ((this.OnTheWayDateField.Equals(value) != true)) {
                    this.OnTheWayDateField = value;
                    this.RaisePropertyChanged("OnTheWayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderSPNotMovableID {
            get {
                return this.OrderSPNotMovableIDField;
            }
            set {
                if ((this.OrderSPNotMovableIDField.Equals(value) != true)) {
                    this.OrderSPNotMovableIDField = value;
                    this.RaisePropertyChanged("OrderSPNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SurveyResultReceivedDate {
            get {
                return this.SurveyResultReceivedDateField;
            }
            set {
                if ((this.SurveyResultReceivedDateField.Equals(value) != true)) {
                    this.SurveyResultReceivedDateField = value;
                    this.RaisePropertyChanged("SurveyResultReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SurveyorID {
            get {
                return this.SurveyorIDField;
            }
            set {
                if ((this.SurveyorIDField.Equals(value) != true)) {
                    this.SurveyorIDField = value;
                    this.RaisePropertyChanged("SurveyorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SyncStatus {
            get {
                return this.SyncStatusField;
            }
            set {
                if ((this.SyncStatusField.Equals(value) != true)) {
                    this.SyncStatusField = value;
                    this.RaisePropertyChanged("SyncStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOrderCode {
            get {
                return this.WorkOrderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderCodeField, value) != true)) {
                    this.WorkOrderCodeField = value;
                    this.RaisePropertyChanged("WorkOrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderNotMovableID {
            get {
                return this.WorkOrderNotMovableIDField;
            }
            set {
                if ((this.WorkOrderNotMovableIDField.Equals(value) != true)) {
                    this.WorkOrderNotMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte WorkOrderStatusID {
            get {
                return this.WorkOrderStatusIDField;
            }
            set {
                if ((this.WorkOrderStatusIDField.Equals(value) != true)) {
                    this.WorkOrderStatusIDField = value;
                    this.RaisePropertyChanged("WorkOrderStatusID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkOrderNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingPeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCondition {
            get {
                return this.CompanyConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyConditionField, value) != true)) {
                    this.CompanyConditionField = value;
                    this.RaisePropertyChanged("CompanyCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyPeriod {
            get {
                return this.CompanyPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPeriodField, value) != true)) {
                    this.CompanyPeriodField = value;
                    this.RaisePropertyChanged("CompanyPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkOrderNotMovableID {
            get {
                return this.WorkOrderNotMovableIDField;
            }
            set {
                if ((this.WorkOrderNotMovableIDField.Equals(value) != true)) {
                    this.WorkOrderNotMovableIDField = value;
                    this.RaisePropertyChanged("WorkOrderNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingPeriod {
            get {
                return this.WorkingPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingPeriodField, value) != true)) {
                    this.WorkingPeriodField = value;
                    this.RaisePropertyChanged("WorkingPeriod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultPhotoAdditionalNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultPhotoAdditionalNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultPhotoAdditionalNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultPhotoAdditionalNotMovableID {
            get {
                return this.ResultPhotoAdditionalNotMovableIDField;
            }
            set {
                if ((this.ResultPhotoAdditionalNotMovableIDField.Equals(value) != true)) {
                    this.ResultPhotoAdditionalNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultPhotoAdditionalNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrResultReqDocNotMovable", Namespace="http://schemas.datacontract.org/2004/07/GSI.WCFToCustomerPortal")]
    [System.SerializableAttribute()]
    public partial class TrResultReqDocNotMovable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReqDocNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResultReqDocNotMovableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageGuid {
            get {
                return this.ImageGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageGuidField, value) != true)) {
                    this.ImageGuidField = value;
                    this.RaisePropertyChanged("ImageGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReqDocNotMovableID {
            get {
                return this.ReqDocNotMovableIDField;
            }
            set {
                if ((this.ReqDocNotMovableIDField.Equals(value) != true)) {
                    this.ReqDocNotMovableIDField = value;
                    this.RaisePropertyChanged("ReqDocNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultNotMovableID {
            get {
                return this.ResultNotMovableIDField;
            }
            set {
                if ((this.ResultNotMovableIDField.Equals(value) != true)) {
                    this.ResultNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResultReqDocNotMovableID {
            get {
                return this.ResultReqDocNotMovableIDField;
            }
            set {
                if ((this.ResultReqDocNotMovableIDField.Equals(value) != true)) {
                    this.ResultReqDocNotMovableIDField = value;
                    this.RaisePropertyChanged("ResultReqDocNotMovableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowStatus {
            get {
                return this.RowStatusField;
            }
            set {
                if ((this.RowStatusField.Equals(value) != true)) {
                    this.RowStatusField = value;
                    this.RaisePropertyChanged("RowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateCPResultServiceReference.IUpdateCPResultService")]
    public interface IUpdateCPResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateCPResultService/UpdateResultMovableCustomerPortal", ReplyAction="http://tempuri.org/IUpdateCPResultService/UpdateResultMovableCustomerPortalRespon" +
            "se")]
        void UpdateResultMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderMovable _prmWorkOrderMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultMovable _prmResultMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateCPResultService/UpdateResultNotMovableCustomerPortal", ReplyAction="http://tempuri.org/IUpdateCPResultService/UpdateResultNotMovableCustomerPortalRes" +
            "ponse")]
        void UpdateResultNotMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderNotMovable _prmWorkOrderNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateCPResultServiceChannel : GSI.BusinessRuleCore.UpdateCPResultServiceReference.IUpdateCPResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCPResultServiceClient : System.ServiceModel.ClientBase<GSI.BusinessRuleCore.UpdateCPResultServiceReference.IUpdateCPResultService>, GSI.BusinessRuleCore.UpdateCPResultServiceReference.IUpdateCPResultService {
        
        public UpdateCPResultServiceClient() {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateResultMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderMovable _prmWorkOrderMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultMovable _prmResultMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalMovable[] _prmResultPhotoAddtMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocMovable[] _prmResultReqDocMovableList) {
            base.Channel.UpdateResultMovableCustomerPortal(_prmWorkOrderMovable, _prmResultMovable, _prmResultPhotoAddtMovable, _prmResultReqDocMovableList);
        }
        
        public void UpdateResultNotMovableCustomerPortal(GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrWorkOrderNotMovable _prmWorkOrderNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultNotMovable _prmResultNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultPhotoAdditionalNotMovable[] _prmResultPhotoAddtNotMovable, GSI.BusinessRuleCore.UpdateCPResultServiceReference.TrResultReqDocNotMovable[] _prmResultReqDocNotMovableList) {
            base.Channel.UpdateResultNotMovableCustomerPortal(_prmWorkOrderNotMovable, _prmResultNotMovable, _prmResultPhotoAddtNotMovable, _prmResultReqDocNotMovableList);
        }
    }
}
