//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSI.WCFTesting.UpdateCPStatusServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyPointType", Namespace="http://schemas.datacontract.org/2004/07/GSI.Common.Enum")]
    public enum SurveyPointType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Movable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotMovable = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GSIInternalStatus", Namespace="http://schemas.datacontract.org/2004/07/GSI.Common.Enum")]
    public enum GSIInternalStatus : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceivedBySystem = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForAssigment = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForDownload = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForSurvey = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnTheWay = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnTheSpot = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SurveyResultReceived = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Published = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateCPStatusServiceReference.IUpdateCPStatusService")]
    public interface IUpdateCPStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateCPStatusService/UpdateStatusCustomerPortal", ReplyAction="http://tempuri.org/IUpdateCPStatusService/UpdateStatusCustomerPortalResponse")]
        void UpdateStatusCustomerPortal(GSI.WCFTesting.UpdateCPStatusServiceReference.SurveyPointType _prmSPType, long _prmSPID, GSI.WCFTesting.UpdateCPStatusServiceReference.GSIInternalStatus _prmStatus, string _prmUserTakeOver);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateCPStatusServiceChannel : GSI.WCFTesting.UpdateCPStatusServiceReference.IUpdateCPStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCPStatusServiceClient : System.ServiceModel.ClientBase<GSI.WCFTesting.UpdateCPStatusServiceReference.IUpdateCPStatusService>, GSI.WCFTesting.UpdateCPStatusServiceReference.IUpdateCPStatusService {
        
        public UpdateCPStatusServiceClient() {
        }
        
        public UpdateCPStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateCPStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCPStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateStatusCustomerPortal(GSI.WCFTesting.UpdateCPStatusServiceReference.SurveyPointType _prmSPType, long _prmSPID, GSI.WCFTesting.UpdateCPStatusServiceReference.GSIInternalStatus _prmStatus, string _prmUserTakeOver) {
            base.Channel.UpdateStatusCustomerPortal(_prmSPType, _prmSPID, _prmStatus, _prmUserTakeOver);
        }
    }
}
